import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/services/redux/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo List | Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <main className="container  mt-4 mx-auto px-4">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
